#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

cd "$(dirname "$0")"

# Pin to the specific commit for reproducibility
# If there are changes to the data, this can be bumped
REF="a3d96a65e11e2bbca7d22a894e8313ede90a33a3"
API_URL="https://api.github.com/repos/apache/parquet-testing/contents/shredded_variant?ref=${REF}"
README="README.md"

START_MARKER="<!-- BEGIN GENERATED FIXTURE LINKS -->"

# Keep one fixture per distinct reader behaviour, not the whole suite
CASE_FILTER='^case-(001|002|013|040|042|043|083|084|087|089|127|128|133|135|136|137|138)(-INVALID)?(_row-[0-9]+)?\.(parquet|variant\.bin)$'

# Fail on HTTP errors + show them
JSON=$(curl -fsSL "$API_URL")
SELECTED=$(printf '%s\n' "$JSON" | jq -c --arg re "$CASE_FILTER" '.[] | select(.name | test($re))')

# Download the kept fixtures (parquet files and their variant goldens)
printf '%s\n' "$SELECTED" | jq -r '.download_url' | xargs -I {} curl -fLO {}

# Remove previously generated section
# We use a .bak file to avoid clobbering the original
sed -i.bak "/$START_MARKER/,\$d" "$README"
rm -f "${README}.bak"

# Append autogenerated links section
{
  echo
  echo "$START_MARKER"
  echo "<!-- This section is autogenerated. Do not edit manually. -->"
  echo
  echo "## Source of Parquet Fixtures"
  echo

  printf '%s\n' "$SELECTED" | jq -r '"- [\(.name)](\(.html_url))"' | sort

  echo
  echo "<!-- END GENERATED FIXTURE LINKS -->"
} >> "$README"

echo "Finished fetching shredded variant fixtures from parquet-testing repo"
