#!/bin/bash
set -euo pipefail

# Pin to the specific commit for reproducibility
# If there are changes to the data, this can be bumped
REF="d1f14a06f800238b127b51fef6fa6b9feb15ab0b"
API_URL="https://api.github.com/repos/apache/parquet-testing/contents/data/geospatial?ref=${REF}"
README="README.md"

START_MARKER="<!-- BEGIN GENERATED FIXTURE LINKS -->"

JSON="$(curl -s "$API_URL")"

# Download all the parquet fixtures, not the associated config files
# or generation scripts
printf '%s\n' "$JSON" \
  | jq -r '.[] | .download_url' \
  | grep '\.parquet$' \
  | xargs -n 1 wget -N

# Remove previously generated section
# We use a .bak file to avoid clobbering the original
sed -i.bak "/$START_MARKER/,\$d" "$README"
rm -f "${README}.bak"

# Append autogenerated links section
{
  echo
  echo "$START_MARKER"
  echo "<!-- This section is autogenerated. Do not edit manually. -->"
  echo
  echo "## Source of Parquet Fixtures"
  echo

  printf '%s\n' "$JSON" \
    | jq -r '
        .[]
        | select(.name | endswith(".parquet"))
        | "- [\(.name)](\(.html_url))"
      '

  echo
  echo "<!-- END GENERATED FIXTURE LINKS -->"
} >> "$README"