#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

# Pin to the specific commit for reproducibility
# If there are changes to the data, this can be bumped
REF="d1f14a06f800238b127b51fef6fa6b9feb15ab0b"
API_URL="https://api.github.com/repos/apache/parquet-testing/contents/data/geospatial?ref=${REF}"
README="README.md"

START_MARKER="<!-- BEGIN GENERATED FIXTURE LINKS -->"

JSON="$(curl -s "$API_URL")"

# Download all the parquet fixtures, not the associated config files
# or generation scripts
printf '%s\n' "$JSON" \
  | jq -r '.[] | .download_url' \
  | grep '\.parquet$' \
  | xargs -n 1 wget -N

# Remove previously generated section
# We use a .bak file to avoid clobbering the original
sed -i.bak "/$START_MARKER/,\$d" "$README"
rm -f "${README}.bak"

# Append autogenerated links section
{
  echo
  echo "$START_MARKER"
  echo "<!-- This section is autogenerated. Do not edit manually. -->"
  echo
  echo "## Source of Parquet Fixtures"
  echo

  printf '%s\n' "$JSON" \
    | jq -r '
        .[]
        | select(.name | endswith(".parquet"))
        | "- [\(.name)](\(.html_url))"
      '

  echo
  echo "<!-- END GENERATED FIXTURE LINKS -->"
} >> "$README"