// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package dv

import (
	"path/filepath"
	"strconv"
	"testing"

	iceio "github.com/apache/iceberg-go/io"
	"github.com/apache/iceberg-go/puffin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestCrossClientReadJavaSingleBlobDV exercises the full Puffin-to-bitmap path
// against a Java-produced single-blob Puffin file (testdata/deletes/single-blob-dv.puffin,
// regenerated by dev/dv-fixtures/generate.sh). The Puffin layer — magic, footer
// offsets, blob metadata casing, compression flag — is where cross-client
// format bugs actually surface; constructing this file in-memory with Go's
// writer and reading it back proves nothing about Java-Go interop. Reading a
// Java-authored artifact end-to-end through ReadDV does.
func TestCrossClientReadJavaSingleBlobDV(t *testing.T) {
	const (
		referencedDataFile = "s3://warehouse/db/table/data/00000-0-abc.parquet"
		fixture            = "single-blob-dv.puffin"
	)
	wantPositions := []int64{1, 3, 5, 7, 9}

	df, fs := loadJavaPuffinBlob(t, fixture, 0, referencedDataFile)

	bm, err := ReadDV(fs, df)
	require.NoError(t, err)
	assert.Equal(t, int64(len(wantPositions)), bm.Cardinality())
	for _, pos := range wantPositions {
		assert.True(t, bm.Contains(uint64(pos)), "position %d should be set", pos)
	}
}

// TestCrossClientReadJavaMultiBlobDV exercises ReadDV against a Java-produced
// multi-blob Puffin file. Multi-blob layout — independent offsets, per-blob
// referenced-data-file properties, footer ordering — is the place where small
// encoding choices cause silent corruption across clients. Each blob is read
// individually and matched against its declared referenced-data-file rather
// than relying on blob ordering, since the spec doesn't pin order.
func TestCrossClientReadJavaMultiBlobDV(t *testing.T) {
	const fixture = "multi-blob-dv.puffin"
	expected := map[string][]int64{
		"s3://warehouse/db/table/data/file-001.parquet": {0, 100, 200},
		"s3://warehouse/db/table/data/file-002.parquet": {50, 150},
	}

	fixturePath := filepath.Join("testdata", "deletes", fixture)
	abs, err := filepath.Abs(fixturePath)
	require.NoError(t, err)

	fs := iceio.LocalFS{}
	f, err := fs.Open(abs)
	require.NoError(t, err)
	t.Cleanup(func() { f.Close() })

	reader, err := puffin.NewReader(f)
	require.NoError(t, err)

	blobs := reader.Blobs()
	require.Len(t, blobs, len(expected))

	seen := make(map[string]struct{}, len(expected))
	for i, blob := range blobs {
		ref, ok := blob.Properties["referenced-data-file"]
		require.True(t, ok, "blob %d missing referenced-data-file property", i)
		want, ok := expected[ref]
		require.Truef(t, ok, "blob %d references unexpected data file %q", i, ref)
		seen[ref] = struct{}{}

		df, _ := loadJavaPuffinBlob(t, fixture, i, ref)
		bm, err := ReadDV(fs, df)
		require.NoErrorf(t, err, "ReadDV blob %d (ref=%s)", i, ref)
		assert.Equalf(t, int64(len(want)), bm.Cardinality(), "blob %d cardinality", i)
		for _, pos := range want {
			assert.Truef(t, bm.Contains(uint64(pos)),
				"blob %d (ref=%s) missing position %d", i, ref, pos)
		}
	}
	require.Len(t, seen, len(expected), "every expected referenced-data-file must be present exactly once")
}

// TestCrossClientGoSerializeMatchesJavaSingleArrayContainer asserts byte-equal
// envelope output for the narrow case it actually covers: scattered
// low-cardinality positions [1, 3, 5, 7, 9] that fit in a single roaring
// array container. Byte equality is *not* a general cross-client guarantee:
// Java's BitmapPositionDeleteIndex.serialize() runs runLengthEncode() before
// emitting bytes, while Go's RoaringPositionBitmap.Serialize() does not, so
// for range-style deletes (or any input that hits the array→bitmap or
// run-encoded thresholds) the two outputs diverge at the byte level while
// both remaining spec-compliant. End-to-end interop for those cases is
// covered by TestCrossClientReadJavaSingleBlobDV / ...MultiBlobDV.
func TestCrossClientGoSerializeMatchesJavaSingleArrayContainer(t *testing.T) {
	javaBytes := readDVTestData(t, "small-alternating-values-position-index.bin")

	bm := NewRoaringPositionBitmap()
	bm.Set(1)
	bm.Set(3)
	bm.Set(5)
	bm.Set(7)
	bm.Set(9)

	goBytes, err := SerializeDV(bm)
	require.NoError(t, err)

	assert.Equal(t, javaBytes, goBytes,
		"Go-serialized envelope must match Java byte-for-byte for a single-array-container fixture")
}

// TestCrossClientHighKeyFixtureRejected asserts Go rejects the same
// spec-illegal fixture Java rejects: 64maphighvals.bin contains a roaring
// key past the spec's max unsigned-key bound (>2^31-1), which the portable
// 64-bit format does not allow. Java's RoaringPositionBitmap rejects with
// `IllegalArgumentException("Invalid unsigned key")`
// (TestRoaringPositionBitmap.testDeserializeUnsupportedRoaringExample); Go
// must also fail-closed on this input.
//
// This is fail-closed parity, not error-message parity: Go's deserializer
// detects the divergence further down the parse (the high-valued key shifts
// the rest of the stream into garbage and the inner roaring decoder trips
// on a missing serial cookie) rather than via an explicit unsigned-key
// bounds check. The cross-client invariant the test pins is "both clients
// reject this fixture", which is the property that matters for spec
// compliance — emitting it would be a writer bug, and silently accepting
// it would be a reader bug.
func TestCrossClientHighKeyFixtureRejected(t *testing.T) {
	data := readDVTestData(t, "64maphighvals.bin")

	_, err := DeserializeRoaringPositionBitmap(data)
	require.Error(t, err, "Go must reject the high-key fixture that Java rejects as 'Invalid unsigned key'")
}

// loadJavaPuffinBlob opens a Java-produced Puffin fixture from
// testdata/deletes/, locates the blob at blobIdx in the footer, and returns a
// mockDVFile with the absolute file path plus the blob's offset/length so
// ReadDV can dispatch through the normal Puffin reader path. The returned IO
// is a LocalFS that resolves the same absolute path.
func loadJavaPuffinBlob(t *testing.T, fixture string, blobIdx int, referencedDataFile string) (*mockDVFile, iceio.IO) {
	t.Helper()

	abs, err := filepath.Abs(filepath.Join("testdata", "deletes", fixture))
	require.NoError(t, err)

	fs := iceio.LocalFS{}
	f, err := fs.Open(abs)
	require.NoError(t, err)
	defer f.Close()

	reader, err := puffin.NewReader(f)
	require.NoError(t, err)

	blobs := reader.Blobs()
	require.Greaterf(t, len(blobs), blobIdx, "fixture %s has only %d blob(s)", fixture, len(blobs))
	blob := blobs[blobIdx]

	cardStr, ok := blob.Properties["cardinality"]
	require.Truef(t, ok, "blob %d missing cardinality property", blobIdx)
	cardinality, err := strconv.ParseInt(cardStr, 10, 64)
	require.NoErrorf(t, err, "parse cardinality %q", cardStr)

	offset := blob.Offset
	size := blob.Length
	df := newDVTestFile(abs, cardinality, &offset, &size)
	df.referencedDataFile = &referencedDataFile

	return df, fs
}
