#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

cd "$(dirname "$0")"

# Pin to the specific commit for reproducibility.
# Bump REF and FILES together when adding or updating cases.
REF="a3d96a65e11e2bbca7d22a894e8313ede90a33a3"

# Cases chosen to cover distinct shredded-reader paths:
#   004, 006, 012 — primitive typed_value
#   046           — flat shredded object
#   044           — nested shredded object (recursive reassembly)
#   134           — partially-shredded object (typed_value + residual merge)
FILES=(
  case-004.parquet
  case-004_row-0.variant.bin
  case-006.parquet
  case-006_row-0.variant.bin
  case-012.parquet
  case-012_row-0.variant.bin
  case-044.parquet
  case-044_row-0.variant.bin
  case-046.parquet
  case-046_row-0.variant.bin
  case-134.parquet
  case-134_row-0.variant.bin
)

BASE_URL="https://api.github.com/repos/apache/parquet-testing/contents/shredded_variant"
README="README.md"
START_MARKER="<!-- BEGIN GENERATED FIXTURE LINKS -->"

for file in "${FILES[@]}"; do
  echo "Downloading $file..."
  curl -fsSL "${BASE_URL}/${file}?ref=${REF}" \
    | python3 -c 'import sys, json, base64; d = json.load(sys.stdin); sys.stdout.buffer.write(base64.b64decode(d["content"]))' \
    > "$file"
done

# Regenerate the source links section in README.md
sed -i.bak "/$START_MARKER/,\$d" "$README"
rm -f "${README}.bak"

{
  echo
  echo "$START_MARKER"
  echo "<!-- This section is autogenerated. Do not edit manually. -->"
  echo
  echo "## Source of Parquet Fixtures"
  echo
  for file in "${FILES[@]}"; do
    echo "- [${file}](https://github.com/apache/parquet-testing/blob/${REF}/shredded_variant/${file})"
  done
  echo
  echo "<!-- END GENERATED FIXTURE LINKS -->"
} >> "$README"

echo "Done. Pinned to commit ${REF}."
