codecov:
  token: 47dfd1fc-dc72-4d25-b608-eca6508efd05

coverage:
  status:
    project:
      default:
        target: 0
        threshold: null
        base: auto
    patch:
      default:
        target: 0
        threshold: null
        base: auto
