# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: RC
on:
  push:
    tags:
      - '*-rc*'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  archive:
    name: Archive
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare for tag
        run: |
          # Remove the 'v' prefix and any '-rc' suffix from the tag name to isolate the version number
          # For a tag like 'v0.1.0-rc1', this will result in '0.1.0'
          version=${GITHUB_REF_NAME#v}
          version=${version%-rc*}
          # Finds the last occurrence of `-rc` and returns everything after it
          # For a tag like 'v0.1.0-rc1', this will result in '1'
          rc=${GITHUB_REF_NAME##*-rc}
          echo "VERSION=${version}" >> ${GITHUB_ENV}
          echo "RC=${rc}" >> ${GITHUB_ENV}
          echo "VERSION=${version}"
          echo "RC=${rc}"
      - name: Archive
        run: |
          # tar.gz file has the format apache-iceberg-go-<version>-rc<rc>.tar.gz
          # and contains a directory named apache-iceberg-go-<version> with the source
          dir="apache-iceberg-go-${VERSION}"
          tar_gz="apache-iceberg-go-${VERSION}-rc${RC}.tar.gz"
          git archive HEAD --prefix "${dir}/" --output "${tar_gz}"
          sha512sum "${tar_gz}" > "${tar_gz}.sha512"
      - uses: actions/upload-artifact@v4
        with:
          name: archive
          path: |
            apache-iceberg-go-*

  upload:
    name: upload
    needs:
      - archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: archive
      - name: Upload
        run: |
          # TODO: Add support for release notes
          gh release create ${GITHUB_REF_NAME} \
            --prerelease \
            --title "Apache Iceberg Go ${GITHUB_REF_NAME}" \
            --generate-notes \
            --verify-tag \
            apache-iceberg-go-*.tar.gz \
            apache-iceberg-go-*.tar.gz.sha*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
